In [2]:
import numpy as np
import pandas as pd
from collections import Counter 
import matplotlib.pyplot as plt
import math

In [47]:
data_business = pd.read_csv('D:/yelp/business.csv',index_col = 0)
data_business.head()

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,...,Alcohol,RestaurantsDelivery,Smoking,BusinessAcceptsBitcoin,GoodForDancing,DriveThru,Caters,Music,DietaryRestrictions,ByAppointmentOnly
0,pQeaRpvuhoEqudo3uymHIQ,The Empanadas House,404 E Green St,Champaign,IL,61820.0,40.110446,-88.233073,4.5,5,...,'none',True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
1,-LfTBo0oa_uD454ScEW2XA,Merry Ann's Diner,1 E Main St,Champaign,IL,61820.0,40.118133,-88.242900,3.0,47,...,u'none',True,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN
2,R32Yh0XxxanldkIp11fuRg,BoBo's BBQ,1511 W Springfield Ave,Champaign,IL,61821.0,40.112515,-88.271575,3.5,45,...,u'none',True,NaN,False,NaN,NaN,True,NaN,NaN,NaN
3,uJIIgBmcIn-Ye-anrqK0DQ,Dunkin',1302 N. Prospect Ave,Champaign,IL,61820.0,40.128653,-88.257411,2.0,18,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4Vig7oCo9P-j2OnPUfaXCA,Papa John's Pizza,1307 E Florida Ave,Urbana,IL,61801.0,40.098003,-88.192751,2.0,5,...,u'none',True,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN

In [48]:
#get frequencies of categories in the dataset
category_frequency = []
num_tags = []

for i in range(data_business.shape[0]):
    each_line = data_business['category'][i].split(", ")
    for content in each_line:
        category_frequency.append(content)
        num_tags.append(len(content))

In [49]:
#count the categories whose frequencies are over 10
new_feature = Counter(category_frequency).most_common(63)

feature = pd.DataFrame()
for ind,val in enumerate(new_feature[2:]):
    feature.loc[ind,'Feature'] = val[0]
    feature.loc[ind,'IDF'] =  math.log1p(len(data_business.business_id) / val[1])

In [51]:
data_business2 = data_business

for ind in range(feature.shape[0]):
    ft = feature.loc[ind,'Feature']
    for i in range(data_business2.shape[0]):
        each_line = data_business2['category'][i].split(", ")
        if ft in each_line:
            data_business2.loc[i,ft] = 1 
        else:
            data_business2.loc[i,ft] = 0

In [62]:
data_business2.head()

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,...,Fashion,Food Delivery Services,Vegetarian,Ethnic Food,Tex-Mex,Breweries,Beauty & Spas,Department Stores,Automotive,Bagels
0,pQeaRpvuhoEqudo3uymHIQ,The Empanadas House,404 E Green St,Champaign,IL,61820.0,40.110446,-88.233073,4.5,5,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1,-LfTBo0oa_uD454ScEW2XA,Merry Ann's Diner,1 E Main St,Champaign,IL,61820.0,40.118133,-88.242900,3.0,47,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,R32Yh0XxxanldkIp11fuRg,BoBo's BBQ,1511 W Springfield Ave,Champaign,IL,61821.0,40.112515,-88.271575,3.5,45,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,uJIIgBmcIn-Ye-anrqK0DQ,Dunkin',1302 N. Prospect Ave,Champaign,IL,61820.0,40.128653,-88.257411,2.0,18,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,4Vig7oCo9P-j2OnPUfaXCA,Papa John's Pizza,1307 E Florida Ave,Urbana,IL,61801.0,40.098003,-88.192751,2.0,5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
data_business2.to_csv('D:/yelp/business_cj.csv')